import { NavigationData } from "@/lib/types/navigation";

export const NAVIGATION_DATA: NavigationData = [
  {
    id: "main",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        href: "/dashboard",
        icon: "Home",
        description: "Your learning overview and progress",
      },
      {
        id: "assessment",
        label: "Placement Test",
        href: "/assessment",
        icon: "ClipboardCheck",
        description: "Take or retake your proficiency assessment",
      },
    ],
  },
  {
    id: "learning",
    title: "Learning",
    items: [
      {
        id: "lessons",
        label: "AI Lessons",
        href: "/lessons",
        icon: "BookOpen",
        isComingSoon: true,
        description: "Personalized lessons generated by AI",
      },
      {
        id: "flashcards",
        label: "Flashcards",
        href: "/flashcards",
        icon: "Brain",
        isComingSoon: true,
        description: "Spaced repetition vocabulary practice",
      },
      {
        id: "conversation",
        label: "Conversation",
        href: "/conversation",
        icon: "MessageCircle",
        isComingSoon: true,
        description: "Real-time AI conversation practice",
      },
    ],
  },
  {
    id: "tools",
    title: "Tools",
    items: [
      {
        id: "dictionary",
        label: "Dictionary",
        href: "/dictionary",
        icon: "Search",
        isComingSoon: true,
        description: "Look up Chinese words and characters",
      },
      {
        id: "progress",
        label: "Progress",
        href: "/progress",
        icon: "TrendingUp",
        isComingSoon: true,
        description: "Track your learning journey",
      },
    ],
  },
  {
    id: "account",
    title: "Account",
    items: [
      {
        id: "profile",
        label: "Profile",
        href: "/profile",
        icon: "User",
        isComingSoon: true,
        description: "Manage your account settings",
      },
      {
        id: "settings",
        label: "Settings",
        href: "/settings",
        icon: "Settings",
        isComingSoon: true,
        description: "Customize your learning experience",
      },
    ],
  },
];
