import { NavigationData } from "@/lib/types/navigation";

export const NAVIGATION_DATA: NavigationData = [
  {
    id: "main",
    items: [
      {
        id: "dashboard",
        label: "Dashboard",
        href: "/dashboard",
        icon: "Home",
        description: "Your learning overview and progress",
      },
      {
        id: "assessment",
        label: "Placement Test",
        href: "/assessment",
        icon: "ClipboardCheck",
        description: "Take or retake your proficiency assessment",
      },
    ],
  },
  {
    id: "learning",
    title: "Learning",
    items: [
      {
        id: "lessons",
        label: "AI Lessons",
        href: "/lessons",
        icon: "BookOpen",
        isComingSoon: false,
        description: "Personalized lessons generated by AI",
      },
      {
        id: "curriculum",
        label: "Curriculum",
        href: "/curriculum",
        icon: "GraduationCap",
        isComingSoon: false,
        description: "Guided path through units and lessons",
      },
      {
        id: "flashcards",
        label: "Flashcards",
        href: "/flashcards",
        icon: "Brain",
        isComingSoon: false,
        description: "Spaced repetition vocabulary practice",
      },
      {
        id: "conversations",
        label: "Conversations",
        href: "/conversations",
        icon: "MessageCircle",
        isComingSoon: false,
        description: "Practice natural dialogues with AI",
      },
    ],
  },
  {
    id: "tools",
    title: "Tools",
    items: [
      {
        id: "dictionary",
        label: "Dictionary",
        href: "/dictionary",
        icon: "Search",
        isComingSoon: false,
        description: "Look up Chinese words and characters",
      },
      {
        id: "progress",
        label: "Progress",
        href: "/progress",
        icon: "TrendingUp",
        isComingSoon: false,
        description: "Track your learning journey",
      },
    ],
  },
  {
    id: "account",
    title: "Account",
    items: [
      {
        id: "profile",
        label: "Profile",
        href: "/profile",
        icon: "User",
        isComingSoon: false,
        description: "Manage your account settings",
      },
      {
        id: "usage",
        label: "Usage",
        href: "/account/usage",
        icon: "Activity",
        isComingSoon: false,
        description: "View your usage and limits",
      },
      {
        id: "billing",
        label: "Billing",
        href: "/account/billing",
        icon: "CreditCard",
        isComingSoon: false,
        description: "Manage your subscription and billing",
      },
      {
        id: "settings",
        label: "Settings",
        href: "/settings",
        icon: "Settings",
        isComingSoon: true,
        description: "Customize your learning experience",
      },
    ],
  },
];
